import { SchemeInfo, MandiRecord } from "./types";

export const UI_TRANSLATIONS = {
  en: {
    title: "AI Kisan Mitra",
    subtitle: "Har Kisan Ka Digital Saathi",
    slogan: "Empowering Rural India with Advanced AI Agritech Insights",
    navDashboard: "My Farm Home",
    navDisease: "Disease Detection",
    navMandi: "Live Mandi Prices",
    navSoil: "Soil Analyzer",
    navGov: "Govt Schemes",
    navFertilizer: "Fertilizer Planner",
    navWater: "Water Guide",
    navPest: "Pest Alerts",
    navOfficer: "Officer Hub",
    welcomeBack: "Welcome back,",
    cropDiseaseTitle: "AI Crop Disease Diagnostician",
    cropDiseaseSub: "Take a picture or upload infected crop images to run immediate lab-grade pathogen detection",
    analyzeSoilTitle: "AI Soil Health & Nutrient Auditor",
    analyzeSoilSub: "Input soil readings or scan a physical report to get exact mineral recommendations",
    liveMandiTitle: "Live Mandi Commodity Tickers",
    liveMandiSub: "Real-time crop rates, historical pricing trend estimations, and nearest district mandis",
    govSchemesTitle: "Government Schemes & Subsidies",
    govSchemesSub: "Translate complex paperwork into step-by-step guidance for PM-Kisan, Fasal Bima, and more",
    fertilizerCalcTitle: "Smart Mineral Dosage Calculator",
    fertilizerCalcSub: "Calculate exact bags of Urea, DAP, and Potash needed for your next harvest",
    waterTitle: "Smart Irrigation & Water Management",
    waterTitleSub: "Precision scheduling guides to maximize soil moisture and conserve groundwater resources",
    pestNetworkTitle: "District Pest Outbreak Warning Network",
    pestNetworkSub: "Report pest infestations and check community warning heatmaps across your district",
    officerHubTitle: "Agriculture Officers Command Center",
    officerHubSub: "Review regional statistics, disease outbreak charts, pest hotzones, and issue warnings",
    chatAssistantTitle: "Expert Ag-Advisor Chat",
    talkingAI: "AI Voice Advisor is speaking...",
    speakNow: "Press & Speak (Hindi / Punjabi / English)...",
    listening: "Listening...",
    logout: "Log Out",
    changeLang: "Choose Language",
    roleFarmer: "Farmer",
    roleOfficer: "Agriculture Officer",
    roleAdmin: "District Administrator",
  },
  hi: {
    title: "एआई किसान मित्र",
    subtitle: "हर किसान का डिजिटल साथी",
    slogan: "उन्नत एआई कृषि तकनीक के साथ ग्रामीण भारत को सशक्त बनाना",
    navDashboard: "मेरा फार्म होम",
    navDisease: "फसल रोग पहचान",
    navMandi: "मंडी भाव",
    navSoil: "मिट्टी जांच",
    navGov: "सरकारी योजनाएं",
    navFertilizer: "खाद कैलकुलेटर",
    navWater: "सिंचाई गाइड",
    navPest: "कीट अलर्ट",
    navOfficer: "अधिकारी हब",
    welcomeBack: "आपका स्वागत है,",
    cropDiseaseTitle: "एआई फसल रोग पहचान केंद्र",
    cropDiseaseSub: "फसल की फोटो लें या अपलोड करें और तुरंत सटीक बीमारी का पता लगाएं",
    analyzeSoilTitle: "एआई मृदा स्वास्थ्य एवं पोषक तत्व परीक्षक",
    analyzeSoilSub: "मिट्टी का विवरण दर्ज करें या रिपोर्ट स्कैन करें और सटीक खाद का सुझाव पाएं",
    liveMandiTitle: "लाइव मंडी कृषि बाजार भाव",
    liveMandiSub: "वास्तविक समय मंडी दरें, मूल्य रुझान और निकटतम सरकारी मंडी केंद्र",
    govSchemesTitle: "सरकारी कृषि योजनाएं और सब्सिडी",
    govSchemesSub: "पीएम-किसान, फसल बीमा और सब्सिडी लाभ समझने की आसान गाइड",
    fertilizerCalcTitle: "स्मार्ट खाद खुराक कैलकुलेटर",
    fertilizerCalcSub: "अपनी अगली फसल के लिए यूरिया, डीएपी और पोटाश की सटीक मात्रा मापें",
    waterTitle: "स्मार्ट सिंचाई एवं जल प्रबंधन",
    waterTitleSub: "मिट्टी की नमी बढ़ाने और भूजल बचाने के लिए सटीक सिंचाई कार्यक्रम",
    pestNetworkTitle: "जिला स्तर कीट प्रकोप चेतावनी प्रणाली",
    pestNetworkSub: "कीटों के हमले की सूचना दें और अपने जिले में कीट चेतावनी मैप देखें",
    officerHubTitle: "कृषि अधिकारी कमांड सेंटर",
    officerHubSub: "क्षेत्रीय रिपोर्ट, रोग के प्रकोप के चार्ट, हॉटजोन की समीक्षा करें और अलर्ट जारी करें",
    chatAssistantTitle: "विशेषज्ञ कृषि एआई सलाहकार",
    talkingAI: "संभाषण एआई बोल रहा है...",
    speakNow: "दबाएं और बोलें (हिंदी / पंजाबी / अंग्रेजी)...",
    listening: "सुन रहा हूँ...",
    logout: "लॉग आउट",
    changeLang: "भाषा चुनें",
    roleFarmer: "किसान साथी",
    roleOfficer: "कृषि अधिकारी",
    roleAdmin: "जिला प्रशासक",
  },
  pa: {
    title: "ਏਆਈ ਕਿਸਾਨ ਮਿੱਤਰ",
    subtitle: "ਹਰ ਕਿਸਾਨ ਦਾ ਡਿਜੀਟਲ ਸਾਥੀ",
    slogan: "ਉੱਨਤ ਏਆਈ ਖੇਤੀਬਾੜੀ ਤਕਨਾਲੋਜੀ ਨਾਲ ਪੇਂਡੂ ਭਾਰਤ ਨੂੰ ਮਜ਼ਬੂਤ ਬਣਾਉਣਾ",
    navDashboard: "ਮੇਰਾ ਫਾਰਮ ਹੋਮ",
    navDisease: "ਫਸਲ ਬਿਮਾਰੀ ਜਾਂਚ",
    navMandi: "ਮੰਡੀ ਦੇ ਭਾਅ",
    navSoil: "ਮਿੱਟੀ ਦੀ ਜਾਂਚ",
    navGov: "ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    navFertilizer: "ਖਾਦ ਕੈਲਕੁਲੇਟਰ",
    navWater: "ਸਿੰਚਾਈ ਗਾਈਡ",
    navPest: "ਕੀੜੇ-ਮਕੌੜੇ ਚੇਤਾਵਨੀ",
    navOfficer: "ਅਫਸਰ ਹੱਬ",
    welcomeBack: "ਜੀ ਆਇਆਂ ਨੂੰ,",
    cropDiseaseTitle: "ਏਆਈ ਫਸਲ ਬਿਮਾਰੀ ਜਾਂਚ ਕੇਂਦਰ",
    cropDiseaseSub: "ਫਸਲ ਦੀ ਫੋਟੋ ਲਓ ਜਾਂ ਅਪਲੋਡ ਕਰੋ ਅਤੇ ਤੁਰੰਤ ਬਿਮਾਰੀ ਦਾ ਪਤਾ ਲਗਾਓ",
    analyzeSoilTitle: "ਏਆਈ ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਅਤੇ ਪੋਸ਼ਕ ਤੱਤ ਟੈਸਟਰ",
    analyzeSoilSub: "ਮਿੱਟੀ ਦੀ ਜਾਂਚ ਦਾ ਵੇਰਵਾ ਭਰੋ ਜਾਂ ਰਿਪੋਰਟ ਸਕੈਨ ਕਰੋ ਅਤੇ ਖਾਦਾਂ ਦੀ ਜਾਣਕਾਰੀ ਲਓ",
    liveMandiTitle: "ਲਾਈਵ ਮੰਡੀ ਫਸਲ ਦੇ ਰੇਟ",
    liveMandiSub: "ਸਹੀ ਸਮੇਂ ਦੀਆਂ ਮੰਡੀ ਦਰਾਂ, ਇਤਿਹਾਸਕ ਰੁਝਾਨ ਅਤੇ ਨੇੜਲੀਆਂ ਸਰਕਾਰੀ ਮੰਡੀਆਂ",
    govSchemesTitle: "ਸਰਕਾਰੀ ਖੇਤੀਬਾੜੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਸਬਸਿਡੀਆਂ",
    govSchemesSub: "ਪੀਐਮ-ਕਿਸਾਨ, ਫਸਲ ਬੀਮਾ ਅਤੇ ਸਬਸिਡੀ ਦੇ ਲਾਭਾਂ ਨੂੰ ਸਮਝਣ ਦੀ ਸੌਖੀ ਗਾਈਡ",
    fertilizerCalcTitle: "ਸਮਾਰਟ ਖਾਦ ਮਾਤਰਾ ਕੈਲਕੁਲੇਟਰ",
    fertilizerCalcSub: "ਆਪਣੀ ਫਸਲ ਲਈ ਯੂਰੀਆ, ਡੀਏਪੀ ਅਤੇ ਪੋਟਾਸ਼ ਦੀ ਸਹੀ ਮਾਤਰਾ ਦੀ ਗਣਨਾ ਕਰੋ",
    waterTitle: "ਸਮਾਰਟ ਸਿੰਚਾਈ ਅਤੇ ਜਲ ਪ੍ਰਬੰਧਨ",
    waterTitleSub: "ਮਿੱਟੀ ਦੀ ਨਮੀ ਵਧਾਉਣ ਅਤੇ ਪਾਣੀ ਬਚਾਉਣ ਲਈ ਸਹੀ ਸਿੰਚਾਈ ਗਾਈਡ",
    pestNetworkTitle: "ਜ਼ਿਲ੍ਹਾ ਪੱਧਰੀ ਕੀੜੇ-ਮਕੌੜੇ ਚੇਤਾਵਨੀ ਸਿਸਟਮ",
    pestNetworkSub: "ਕੀੜਿਆਂ ਦੇ ਹਮਲੇ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਅਤੇ ਆਪਣੇ ਇਲਾਕੇ ਦੇ ਚੇਤਾਵਨੀ ਮੈਪ ਦੇਖੋ",
    officerHubTitle: "ਖੇਤੀਬਾੜੀ ਅਫਸਰ ਕਮਾਂਡ ਸੈਂਟਰ",
    officerHubSub: "ਜ਼ਿਲ੍ਹੇ ਦੀਆਂ ਰਿਪੋਰਟਾਂ, ਬਿਮਾਰੀ ਦੇ ਚਾਰਟ ਅਤੇ ਅਲਰਟ ਜਾਰੀ ਕਰਨ ਲਈ ਕੇਂਦਰ",
    chatAssistantTitle: "ਮਾਹਰ ਖੇਤੀਬਾੜੀ ਏਆਈ ਸਲਾਹਕਾਰ",
    talkingAI: "ਸੰਭਾਸ਼ਣ ਏਆਈ ਬੋਲ ਰਿਹਾ ਹੈ...",
    speakNow: "ਦਬਾਓ ਅਤੇ ਬੋਲੋ (ਪੰਜਾਬੀ / ਹਿੰਦੀ / ਅੰਗਰੇਜ਼ੀ)...",
    listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
    logout: "ਲੌਗ ਆਉਟ",
    changeLang: "ਭਾਸ਼ਾ ਚੁਣੋ",
    roleFarmer: "ਕਿਸਾਨ ਵੀਰ",
    roleOfficer: "ਖੇਤੀਬਾੜੀ ਅਫਸਰ",
    roleAdmin: "ਜ਼ਿਲ੍ਹਾ ਪ੍ਰਸ਼ਾਸਕ",
  },
};

export const MOCK_WEATHER_DATA = {
  temp: 34,
  humidity: 62,
  rainProbability: 15,
  windSpeed: 12,
  uvIndex: 8,
  condition: "Mostly Sunny",
  aiRecommendation: {
    en: "Temperature is high with 62% humidity. Sowing under dry ground not advised. Check moisture levels before cotton spraying. Topsoil contains high heat indices.",
    hi: "तापमान अधिक है और उमस 62% है। सूखी जमीन में बुआई न करें। कपास पर छिड़काव करने से पहले मिट्टी की नमी की जांच कर लें।",
    pa: "ਤਾਪਮਾਨ ਉੱਚਾ ਹੈ ਅਤੇ ਨਮੀ 62% ਹੈ। ਸੁੱਕੀ ਜ਼ਮੀਨ ਵਿੱਚ ਬਿਜਾਈ ਨਾ ਕਰੋ। ਨਰਮੇ ਉੱਤੇ ਸਪਰੇਅ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਨਮੀ ਚੈੱਕ ਕਰੋ।"
  }
};

export const PRESET_PUNJAB_DISTRICTS = [
  "Ludhiana", "Patiala", "Amritsar", "Bathinda", "Jalandhar", "Sangrur", "Fazilka", "Ferozepur", "Gurdaspur"
];
export const PRESET_HARYANA_DISTRICTS = [
  "Karnal", "Sirsa", "Hisar", "Ambala", "Sonipat", "Panipat", "Rohtak", "Kurukshetra"
];
export const PRESET_UP_DISTRICTS = [
  "Agra", "Meerut", "Lucknow", "Varanasi", "Bareilly", "Gorakhpur", "Jhansi"
];

export const MOCK_PEST_HISTORY = [
  { id: "p1", reporterName: "Sukhdev Singh", district: "Bathinda", state: "Punjab", cropType: "Cotton", pestName: "Pink Bollworm (गुलाबी सुंडी)", severity: "high", createdAt: "2026-06-06", description: "Widespread attack observed in cotton fields near bypass road." },
  { id: "p2", reporterName: "Ramesh Sharma", district: "Karnal", state: "Haryana", cropType: "Paddy", pestName: "Stem Borer (तना छेदक)", severity: "medium", createdAt: "2026-06-05", description: "Light yellow patches across 5 acres. Seeking pesticide support." },
  { id: "p3", reporterName: "Baldev Singh", district: "Sangrur", state: "Punjab", cropType: "Wheat", pestName: "Aphids (ਚੇਪਾ)", severity: "low", createdAt: "2026-06-07", description: "Infestation localized near border hedges. Soil is well hydrated." },
  { id: "p4", reporterName: "Amit Verma", district: "Agra", state: "Uttar Pradesh", cropType: "Potato", pestName: "Late Blight (झुलसा रोग)", severity: "high", createdAt: "2026-06-04", description: "Widespread fungal symptoms visible on stems. Quick spraying needed." },
];
